package:
 name: t_sne_bhcuda
 version: 0.2.0



source:
 fn: t_sne_bhcuda-0.2.0.zip
 md5:
 url: https://pypi.python.org/packages/source/t/t_sne_bhcuda/t_sne_bhcuda-0.2.0.zip

requirements:
 build:
  - python
 run:
  - python
  - bokeh
  - numpy
  - scipy
  - pandas


