package:
 name: t_sne_bhcuda
 version: 0.1.0

source:
 git_rev: 0.1
 git_url: https://github.com/georgedimitriadis/t_sne_bhcuda.git


build:
 preserve_egg_dir: False
 rpaths:
  - bin/linux


requirements:
 run:
  - python