package:
 name: t_sne_bhcuda
 version: 0.1.6



source:
 fn: t_sne_bhcuda-0.1.6.zip
 md5: 24f54be6eaf94f9ffb5dee197700d276
 url: https://pypi.python.org/packages/source/t/t_sne_bhcuda/t_sne_bhcuda-0.1.6.zip

requirements:
 build:
  - python
 run:
  - python


